"""Stable JSON and polished HTML rendering for the local web dashboard."""

from dataclasses import asdict
import json


class WebDashboardRenderer:
    def json(self, view):
        return json.dumps(asdict(view), default=str, sort_keys=True, separators=(",", ":"))

    def html(self, view):
        """Return a static presentation shell; data arrives from the GET-only API."""
        refresh = int(view.refresh_seconds)
        return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark"><title>Hermes Quant Labs | PAPER Operator Dashboard</title>
<style>
:root{{--bg:#070b11;--panel:#0d141e;--panel2:#111b28;--line:#213044;--text:#edf4fb;--muted:#8fa2b8;--cyan:#36d7e7;--blue:#4d88ff;--green:#46d596;--amber:#f5b942;--red:#ff647c;--violet:#a78bfa;--shadow:0 18px 50px rgba(0,0,0,.28)}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;overflow-x:hidden;background:radial-gradient(circle at 85% -10%,#14304d 0,transparent 32rem),var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}}
.shell{{max-width:1600px;margin:auto;padding:22px}}header{{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:18px}}.brand{{display:flex;align-items:center;gap:13px}}.mark{{width:38px;height:38px;border:1px solid #3c586f;border-radius:11px;background:linear-gradient(145deg,#18314a,#0a111b);display:grid;place-items:center;color:var(--cyan);font-weight:900;letter-spacing:-2px;box-shadow:inset 0 0 20px #1c567455}}h1{{font-size:19px;line-height:1.1;margin:0;letter-spacing:.02em}}.sub{{color:var(--muted);font-size:12px;margin-top:4px}}.header-meta{{text-align:right;color:var(--muted);font-size:12px}}.refresh{{display:inline-flex;align-items:center;gap:7px}}.dot{{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green)}}
.paper-banner{{display:flex;justify-content:center;align-items:center;gap:10px;background:linear-gradient(90deg,#49320c,#2f220d,#49320c);border:1px solid #a9751e;color:#ffd77a;border-radius:10px;padding:9px 14px;margin-bottom:18px;font-weight:850;letter-spacing:.14em;font-size:12px}}
.status-grid,.metric-grid{{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}}.card,.section{{background:linear-gradient(150deg,rgba(17,27,40,.96),rgba(11,18,27,.96));border:1px solid var(--line);border-radius:13px;box-shadow:var(--shadow)}}.card{{padding:14px;min-height:88px}}.label{{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.11em}}.value{{font-size:17px;font-weight:760;margin-top:7px;overflow-wrap:anywhere}}.detail{{font-size:11px;color:var(--muted);margin-top:3px}}.good{{color:var(--green)}}.warn{{color:var(--amber)}}.bad{{color:var(--red)}}.info{{color:var(--cyan)}}
.section{{padding:18px;margin-top:14px;min-width:0}}.section-head{{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;margin-bottom:14px}}h2{{font-size:15px;margin:0;letter-spacing:.02em}}.section-copy{{color:var(--muted);font-size:11px}}.metric-grid{{grid-template-columns:repeat(6,minmax(0,1fr));margin-bottom:14px}}.metric-grid .card{{min-height:78px;background:#0a121c}}
.market-grid{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}}.market{{padding:15px;border-radius:12px;background:#0a121c;border:1px solid var(--line)}}.market-top{{display:flex;justify-content:space-between;align-items:center}}.symbol{{font-weight:800;font-size:16px}}.price{{font-size:22px;font-weight:750;margin:13px 0 7px}}.kv{{display:grid;grid-template-columns:1fr auto;gap:5px 10px;font-size:12px}}.kv span:nth-child(odd){{color:var(--muted)}}
.table-wrap{{overflow:auto;border:1px solid var(--line);border-radius:10px}}table{{width:100%;border-collapse:collapse;min-width:760px}}th,td{{padding:10px 12px;text-align:left;border-bottom:1px solid #1a2838;white-space:nowrap}}th{{background:#0a121c;color:#8296ad;font-size:10px;text-transform:uppercase;letter-spacing:.09em;position:sticky;top:0}}td{{font-size:12px}}tr:last-child td{{border-bottom:0}}.empty{{padding:26px;text-align:center;color:var(--muted);border:1px dashed #29405a;border-radius:10px;background:#09111a}}
.two-col{{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}}.explain-grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}}.explain{{background:#09111a;border:1px solid var(--line);border-radius:10px;padding:13px}}.explain h3{{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--cyan);margin:0 0 8px}}.explain p,.explain ul{{margin:0;color:#c4d0dc}}.explain ul{{padding-left:18px}}.full{{grid-column:1/-1}}.providers{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}}.provider{{padding:14px;background:#09111a;border:1px solid var(--line);border-radius:10px}}
.charts{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}}.chart{{padding:13px;background:#09111a;border:1px solid var(--line);border-radius:10px;min-height:220px}}.chart h3{{font-size:12px;margin:0 0 6px}}canvas{{display:block;width:100%;height:160px}}.chart-empty{{height:160px;display:grid;place-items:center;color:var(--muted)}}.disclaimer{{font-size:10px;color:var(--muted);margin-top:9px}}
.activity-grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}}.activity,.chart,.market,.provider,.card{{min-width:0}}.activity h3{{font-size:12px;margin:0 0 8px}}.alert{{padding:10px 12px;border-left:3px solid var(--amber);background:#2b2112;margin-bottom:7px;border-radius:4px;color:#e7d1a2}}footer{{padding:24px 4px 8px;color:var(--muted);font-size:11px;text-align:center}}
#refresh-warning{{display:none;background:#421c24;border:1px solid #913849;color:#ffbdc7;padding:10px 14px;border-radius:9px;margin-bottom:12px}}#refresh-warning.show{{display:block}}
@media(max-width:1100px){{.status-grid{{grid-template-columns:repeat(3,1fr)}}.metric-grid{{grid-template-columns:repeat(3,1fr)}}.market-grid{{grid-template-columns:repeat(2,1fr)}}.two-col{{grid-template-columns:1fr}}}}
@media(max-width:720px){{.shell{{padding:13px}}header{{align-items:flex-start}}.header-meta{{max-width:170px}}.status-grid,.metric-grid,.market-grid,.providers,.charts,.activity-grid,.explain-grid{{grid-template-columns:1fr 1fr}}.full{{grid-column:1/-1}}}}
@media(max-width:480px){{.status-grid,.metric-grid,.market-grid,.providers,.charts,.activity-grid,.explain-grid{{grid-template-columns:1fr}}.full{{grid-column:auto}}}}
</style></head><body><div class="shell">
<header><div class="brand"><div class="mark" aria-hidden="true">H</div><div><h1>Hermes Quant Labs</h1><div class="sub">Hermes OS <span id="version">—</span> · Local operator console</div></div></div><div class="header-meta"><div class="refresh"><span class="dot"></span><span>Auto-refresh · {refresh}s</span></div><div>Updated <span id="updated">Awaiting data</span></div></div></header>
<div class="paper-banner">● PAPER MODE ONLY · SIMULATED EXECUTION · READ ONLY</div><div id="refresh-warning" role="alert">Dashboard refresh failed. Retaining the last known display and retrying automatically.</div>
<main><section class="status-grid" id="status-cards" aria-label="System status"></section>
<section class="section"><div class="section-head"><div><h2>Portfolio</h2><div class="section-copy">Simulated capital and persisted PAPER positions</div></div></div><div class="metric-grid" id="portfolio-metrics"></div><h3>Open positions</h3><div id="open-positions"></div><h3>Closed trades</h3><div id="closed-trades"></div></section>
<section class="section"><div class="section-head"><div><h2>Markets</h2><div class="section-copy">Latest validated public observations by enabled symbol</div></div></div><div class="market-grid" id="markets"></div></section>
<div class="two-col"><section class="section"><div class="section-head"><div><h2>Specialist intelligence</h2><div class="section-copy">Included, excluded, and weighted evidence</div></div></div><div id="specialists"></div></section>
<section class="section"><div class="section-head"><div><h2>Provider & health</h2><div class="section-copy">Public, unauthenticated market-data providers</div></div></div><div class="providers" id="providers"></div><div id="alerts"></div></section></div>
<section class="section"><div class="section-head"><div><h2>Why Hermes Made This Decision</h2><div class="section-copy">Human-readable evidence, assumptions, uncertainty, and Risk Manager rationale</div></div></div><div class="explain-grid" id="explanation"></div></section>
<section class="section"><div class="section-head"><div><h2>Paper observation charts</h2><div class="section-copy">UTC history · no profitability claim</div></div></div><div class="charts"><div class="chart"><h3>Equity curve</h3><canvas id="equity-chart"></canvas></div><div class="chart"><h3>Cash curve</h3><canvas id="cash-chart"></canvas></div><div class="chart"><h3>Exposure curve</h3><canvas id="exposure-chart"></canvas></div><div class="chart"><h3>Drawdown</h3><canvas id="drawdown-chart"></canvas></div><div class="chart"><h3>Recent symbol prices</h3><canvas id="price-chart"></canvas></div><div class="chart"><h3>Recommendation history</h3><canvas id="recommendation-chart"></canvas></div></div><div class="disclaimer" id="chart-disclaimer"></div></section>
<section class="section"><div class="section-head"><div><h2>Recent activity</h2><div class="section-copy">Bounded read-only history from the local audit journal</div></div></div><div class="activity-grid"><div class="activity"><h3>Recent cycles</h3><div id="recent-cycles"></div></div><div class="activity"><h3>Recent decisions</h3><div id="recent-decisions"></div></div><div class="activity"><h3>Recent fills</h3><div id="recent-fills"></div></div><div class="activity"><h3>Recent learning recommendations</h3><div id="recent-learning"></div></div></div></section></main>
<footer>Hermes OS is a PAPER-only quantitative research platform. Public observations and simulated results do not guarantee future performance.</footer></div>
<script>
"use strict";
const REFRESH_SECONDS={refresh}; let lastData=null;
const esc=v=>String(v??"—").replace(/[&<>"']/g,c=>({{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}}[c]));
const num=v=>Number(v??0); const money=v=>Number.isFinite(num(v))?`$${{num(v).toLocaleString(undefined,{{minimumFractionDigits:2,maximumFractionDigits:2}})}}`:"—";
const pct=v=>Number.isFinite(num(v))?`${{num(v).toFixed(2)}}%`:"—";
const utc=v=>{{if(!v)return "—";const d=new Date(v);return Number.isNaN(d.valueOf())?esc(v):d.toISOString().replace("T"," ").replace(".000Z"," UTC")}};
const tone=v=>{{v=String(v).toUpperCase();return /HEALTHY|APPROVED|LONG|WIN|PAPER/.test(v)?"good":/REJECT|FAIL|STALE|UNHEALTHY|LOSS/.test(v)?"bad":/WAIT|HOLD|WARN|STANDBY|UNKNOWN/.test(v)?"warn":"info"}};
function cards(rows,target){{document.getElementById(target).innerHTML=rows.map(x=>`<article class="card"><div class="label">${{esc(x[0])}}</div><div class="value ${{tone(x[1])}}">${{esc(x[1])}}</div><div class="detail">${{esc(x[2]||"")}}</div></article>`).join("")}}
function table(rows,cols,empty){{if(!rows?.length)return `<div class="empty">${{esc(empty)}}</div>`;return `<div class="table-wrap"><table><thead><tr>${{cols.map(c=>`<th>${{esc(c[0])}}</th>`).join("")}}</tr></thead><tbody>${{rows.map(r=>`<tr>${{cols.map(c=>`<td class="${{c[2]?tone(r[c[1]]):""}}">${{esc(c[3]?c[3](r[c[1]]):r[c[1]])}}</td>`).join("")}}</tr>`).join("")}}</tbody></table></div>`}}
function list(v,empty="None reported"){{return v?.length?`<ul>${{v.map(x=>`<li>${{esc(x)}}</li>`).join("")}}</ul>`:`<p>${{empty}}</p>`}}
function render(d){{lastData=d;document.getElementById("version").textContent=d.version;document.getElementById("updated").textContent=utc(d.updated_at);
cards([["System",d.system_health,"Application and journal"],["Mode",d.mode,"No live transport"],["Database",d.database_health,"SQLite audit journal"],["Provider",d.provider_health,d.active_provider],["Latest cycle",utc(d.latest_cycle_time),"UTC"],["Regime",d.market_regime,"Latest symbol"],["Recommendation",d.current_recommendation,`${{num(d.confidence).toFixed(1)}}% confidence`],["Risk Manager",d.risk_status,d.risk_reason]],"status-cards");
cards([["Starting balance",money(d.starting_balance)],["Cash",money(d.cash)],["Equity",money(d.equity)],["Total return",pct(d.total_return)],["Realized P&L",money(d.realized_pnl)],["Unrealized P&L",money(d.unrealized_pnl)],["Exposure",money(d.exposure)],["Open positions",d.open_position_count],["Closed trades",d.closed_trade_count],["Fees paid",money(d.fees_paid)],["Slippage impact",money(d.slippage_impact)],["Maximum drawdown",money(d.maximum_drawdown)]],"portfolio-metrics");
document.getElementById("open-positions").innerHTML=table(d.open_positions,[["Symbol","symbol"],["Quantity","quantity"],["Average entry","average_entry",false,money],["Current price","current_price",false,money],["Market value","market_value",false,money],["Unrealized P&L","unrealized_pnl",true,money],["Return","unrealized_return",true,pct],["Position age / entry","position_age",false,utc],["Provider","provider"],["Regime","regime"]],"No open PAPER positions.");
document.getElementById("closed-trades").innerHTML=table(d.closed_trades,[["Symbol","symbol"],["Entry time","entry_time",false,utc],["Exit time","exit_time",false,utc],["Entry","entry_price",false,money],["Exit","exit_price",false,money],["Quantity","quantity"],["Fees","fees",false,money],["Realized P&L","realized_pnl",true,money],["Return","return",true,pct],["Duration","trade_duration"],["Result","result",true]],"No closed PAPER trades yet.");
document.getElementById("markets").innerHTML=d.markets.map(m=>`<article class="market"><div class="market-top"><span class="symbol">${{esc(m.symbol)}}</span><span class="${{tone(m.risk_status)}}">${{esc(m.risk_status)}}</span></div><div class="price">${{m.price==null?"No observation":money(m.price)}}</div><div class="kv"><span>Provider</span><b>${{esc(m.provider)}}</b><span>Regime</span><b>${{esc(m.regime)}}</b><span>Recommendation</span><b class="${{tone(m.recommendation)}}">${{esc(m.recommendation)}}</b><span>Confidence</span><b>${{pct(m.confidence)}}</b><span>Last cycle</span><b>${{utc(m.last_cycle_time)}}</b><span>Data freshness</span><b class="${{tone(m.data_freshness)}}">${{esc(m.data_freshness)}}</b><span>Position</span><b>${{m.position_open?"OPEN":"NONE"}}</b><span>Unrealized P&L</span><b>${{m.unrealized_pnl==null?"—":money(m.unrealized_pnl)}}</b></div></article>`).join("");
document.getElementById("specialists").innerHTML=table(d.specialists,[["Specialist","name"],["Conclusion","conclusion",true],["Confidence","confidence",false,pct],["Weighted score","weighted_score"],["Evidence","explanation",false,v=>(v||[]).join(" · ")],["Included","included",true,v=>v?"INCLUDED":"EXCLUDED"],["Inclusion / exclusion reason","exclusion_reason"]],"No specialist result is available.");
document.getElementById("providers").innerHTML=d.providers.map(p=>`<article class="provider"><div class="market-top"><b>${{esc(p.name)}}</b><span class="${{tone(p.status)}}">${{esc(p.status)}}</span></div><div class="kv"><span>Priority</span><b>${{esc(p.priority)}}</b><span>Health score</span><b>${{esc(p.health_score)}}</b><span>Latency</span><b>${{esc(p.latency)}}</b><span>Successes</span><b>${{esc(p.success_count)}}</b><span>Failures</span><b>${{esc(p.failure_count)}}</b><span>Consecutive</span><b>${{esc(p.consecutive_failures)}}</b><span>Cooldown</span><b>${{esc(p.cooldown)}}</b><span>Last success</span><b>${{utc(p.last_success)}}</b></div></article>`).join("");
document.getElementById("alerts").innerHTML=d.recent_alerts?.length?`<h3>Alerts & warnings</h3>${{d.recent_alerts.slice(0,8).map(a=>`<div class="alert">${{esc(a.message||a.detail||a)}}</div>`).join("")}}`:"";
const e=d.explanation||{{}};document.getElementById("explanation").innerHTML=`<div class="explain full"><h3>What is happening</h3><p>${{esc(e.what_is_happening||"No completed decision cycle is available.")}}</p></div><div class="explain"><h3>Recommendation</h3><p>${{esc(e.recommendation||d.current_recommendation)}} · ${{pct(e.confidence??d.confidence)}}</p></div><div class="explain"><h3>Market regime</h3><p>${{esc(d.market_regime)}}</p></div><div class="explain full"><h3>Risk Manager explanation</h3><p>${{esc(e.risk_explanation||d.risk_reason)}}</p></div><div class="explain"><h3>Specialist agreement</h3>${{list(e.agreeing_specialists)}}</div><div class="explain"><h3>Specialist disagreement</h3>${{list(e.disagreeing_specialists)}}</div><div class="explain"><h3>Assumptions</h3>${{list(e.assumptions)}}</div><div class="explain"><h3>Uncertainty</h3>${{list(e.uncertainties)}}</div><div class="explain"><h3>Ignored evidence</h3>${{list(e.ignored_evidence)}}</div><div class="explain"><h3>Why evidence was ignored</h3>${{list(e.ignored_reasons)}}</div>`;
document.getElementById("recent-cycles").innerHTML=table(d.recent_cycles,[["Time","timestamp",false,utc],["Symbol","symbol"],["Provider","provider"],["Status","status",true]],"No cycles recorded.");document.getElementById("recent-decisions").innerHTML=table(d.recent_decisions,[["Time","timestamp",false,utc],["Symbol","symbol"],["Decision","recommendation",true],["Confidence","confidence",false,pct],["Risk","risk_status",true]],"No decisions recorded.");document.getElementById("recent-fills").innerHTML=table(d.recent_fills,[["Time","timestamp",false,utc],["Fill","fill_id"],["Quantity","quantity"],["Price","price",false,money],["Fee","fee",false,money]],"No PAPER fills recorded.");document.getElementById("recent-learning").innerHTML=d.learning_recommendations?.length?table(d.learning_recommendations,[["Recommendation","recommendation"],["Review","human_approval_required",true]],"No learning recommendations."):`<div class="empty">No learning recommendations. Hermes never applies changes automatically.</div>`;
drawCharts(d.charts||{{}});document.getElementById("chart-disclaimer").textContent=d.charts?.disclaimer||"PAPER observations do not guarantee profitability.";}}
function plot(id,series){{const canvas=document.getElementById(id),box=canvas.parentElement,old=box.querySelector(".chart-empty");if(old)old.remove();if(!series.length){{canvas.style.display="none";const e=document.createElement("div");e.className="chart-empty";e.textContent="No PAPER history available";box.appendChild(e);return}}canvas.style.display="block";const ratio=window.devicePixelRatio||1,w=canvas.clientWidth,h=160;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext("2d");c.scale(ratio,ratio);c.clearRect(0,0,w,h);const values=series.map(x=>num(x.value)),min=Math.min(...values),max=Math.max(...values),span=max-min||1;c.strokeStyle="#36d7e7";c.lineWidth=2;c.beginPath();values.forEach((v,i)=>{{const x=8+i*(w-16)/Math.max(1,values.length-1),y=8+(max-v)*(h-22)/span;i?c.lineTo(x,y):c.moveTo(x,y)}});c.stroke();c.fillStyle="#8fa2b8";c.font="10px system-ui";c.fillText(max.toFixed(2),8,10);c.fillText(min.toFixed(2),8,h-4)}}
function drawCharts(c){{const p=c.portfolio||[];plot("equity-chart",p.map(x=>({{value:x.equity}})));plot("cash-chart",p.map(x=>({{value:x.cash}})));plot("exposure-chart",p.map(x=>({{value:x.exposure}})));plot("drawdown-chart",p.map(x=>({{value:x.drawdown}})));plot("price-chart",c.prices||[]);plot("recommendation-chart",c.recommendations||[])}}
async function refresh(){{try{{const response=await fetch("/api/dashboard",{{method:"GET",cache:"no-store",headers:{{Accept:"application/json"}}}});if(!response.ok)throw new Error("dashboard unavailable");const data=await response.json();render(data);document.getElementById("refresh-warning").classList.remove("show")}}catch(error){{document.getElementById("refresh-warning").classList.add("show")}}}}
refresh();setInterval(refresh,REFRESH_SECONDS*1000);window.addEventListener("resize",()=>lastData&&drawCharts(lastData.charts||{{}}));
</script></body></html>'''
